### ISSUE TITLE
console.log() messages not showing in Crashlytics!

### ISSUE THREAD

**Issue by ljhender** [zachgibb/react-native-fabric-android-integration#1]
Hey Zach,

Following your tutorial, I have implemented everything and it looks pretty cool! However, I set up a case where I log something with console.log then crash the app, and that message or any other console.log() message isn't showing up in crashlytics. I am getting some logging however shown here:

![screen shot 2016-08-16 at 11 04 37 am](https://cloud.githubusercontent.com/assets/7491754/17710275/6096a86e-63a1-11e6-8ac8-740e6f33f7be.png)

but not really what I am expecting. Am I missing something?

**Comment by zachgibb** [comment]
How are you crashing the app?

**Comment by ljhender** [comment]
By calling a non existing function after a console.log()
onPress={() => {console.log('AndroidGame','im crashing!');LoginActioned.signOut()}

The LoginActioned is mispelled and doesn't exist, which causes the crash.

**Comment by zachgibb** [comment]
if you go to your MainActivity page, and then change the minimumLoggingLevel to `INFO` of the ReactNativeFabricLogger after you set it as the logging delegate, does that help?

If you check out the [defaultLoggingDelegate docs](https://github.com/facebook/fresco/blob/master/fbcore/src/main/java/com/facebook/common/logging/FLogDefaultLoggingDelegate.java#L25), you can see that the minimumLoggingLevel is set to `WARN` at first. This means that anything under that logging priority should not be logged in the first place. You can change this with the [LoggingDelegate setMinimumLoggingLevel](https://github.com/facebook/fresco/blob/master/fbcore/src/main/java/com/facebook/common/logging/LoggingDelegate.java#L22) method. As arguments, it can take any of the logging levels found in the [android.util.Log docs](https://developer.android.com/reference/android/util/Log.html).

This might not be the issue, but try that out first to see if it helps.

```
++ import android.util.Log;

public class MainActivity extends ReactActivity {
    ...
    public void onCreate(Bundle savedInstanceState) {
        ...
++      ReactNativeFabricLogger.getInstance().setMinimumLoggingLevel(Log.INFO);
    }
```

**Comment by jrm2k6** [comment]
Where do you import CrashlyticsLogger from? It doesn't look like it is possible to import it. I am not able to see crashes from Javascript errors in Crashlytics.

**Comment by zachgibb** [comment]
Oops! I miswrote, instead of CrashlyticsLogger, it should be ReactNativeFabricLogger (the one that we built in the repo). I've updated the earlier comment to reflect that. Thanks for the catch!

**Comment by jrm2k6** [comment]
Cool thanks. It looks like only native APIs errors are caught by Crashlytics, not the JS ones. Any idea how to proceed to debug?

**Comment by ljhender** [comment]
Yeah I actually had this issue too. You can set to verbose but I think more action is needed than just this tutorial to get js logs etc.

**Comment by zachgibb** [comment]
Yeah, I may have been a little hasty in posting it up. I got so excited that I must have assumed what I was seeing is what I wanted to see. I'm in the middle of researching a solution to it. It should be possible, though.

Here's a quick update on where I am so far.

If we have a JS file containing:

``` JSX
<Text
  onPress={() => {
    console.log('im');
    console.log('about');
    console.log('to');
    console.log('crash');
    throw 'I am an error';
  }} >
  Throw error
</Text>
```

we can see in the output of the logs on our device:

```
08-23 20:02:44.390 7955 8019 I ReactNativeJS: im
08-23 20:02:44.390 7955 8019 I ReactNativeJS: about
08-23 20:02:44.390 7955 8019 I ReactNativeJS: to
08-23 20:02:44.390 7955 8019 I ReactNativeJS: crash
08-23 20:02:44.391 7955 8019 E ReactNativeJS: I am an error
```

As a tangent, the "I" and "E" before `ReactNativeJS` seems to be associated with the INFO and ERROR priority levels respectively.

What's interesting though, is that `ReactNativeJS` string before the logs. If I search the React Native project for this string ([link](https://github.com/facebook/react-native/search?utf8=%E2%9C%93&q=ReactNativeJS)), we can see that both instances are calling `FBLOG_PRI` as the logging function.

Following that trail, we can see that it is defined in [fb/log.h](https://github.com/facebook/react-native/blob/ee77e50c4a840f22cd41898584d3d7c1a8b9a492/ReactAndroid/src/main/jni/first-party/fb/include/fb/log.h#L293). FBLOG_PRI calls out to `fb_printlog` [here](https://github.com/facebook/react-native/blob/ee77e50c4a840f22cd41898584d3d7c1a8b9a492/ReactAndroid/src/main/jni/first-party/fb/include/fb/log.h#L293).

Ok. `fb_printlog` is defined [here](https://github.com/facebook/react-native/blob/235b16d93287061a09c4624e612b5dc4f960ce47/ReactAndroid/src/main/jni/first-party/fb/log.cpp#L22), and it seems to imply that [if there is a logging handler set up, it will use that logger](https://github.com/facebook/react-native/blob/235b16d93287061a09c4624e612b5dc4f960ce47/ReactAndroid/src/main/jni/first-party/fb/log.cpp#L30), which can be set just above ([here](https://github.com/facebook/react-native/blob/235b16d93287061a09c4624e612b5dc4f960ce47/ReactAndroid/src/main/jni/first-party/fb/log.cpp#L18)).

This is as far as I've gotten so far, so if anyone else wants to dig in, feel free to make updates in this thread. I'll keep digging until we can figure out a solution, though.

**Comment by zachgibb** [comment]
I haven't really done much in Java or C++, so this might be rough (or inaccurate), but here's my idea, gleaned from some research

[setLogHandler](https://github.com/facebook/react-native/blob/ee77e50c4a840f22cd41898584d3d7c1a8b9a492/ReactAndroid/src/main/jni/first-party/fb/include/fb/log.h#L311) takes a function that expects arguments of (int, string, string)

my initial thought was to use the same method that [ThreadScopeSupport](https://github.com/facebook/react-native/blob/7f790dc0de1ecc9f232e304abcc5e38b9fae98f0/ReactAndroid/src/main/java/com/facebook/jni/ThreadScopeSupport.java) is using to access the [native C++ functions](https://github.com/facebook/react-native/blob/7f790dc0de1ecc9f232e304abcc5e38b9fae98f0/ReactAndroid/src/main/jni/first-party/fb/jni/Environment.cpp#L36) in java, where I would just pass in an anonymous function to a proxy of setLogHandler. That would have been great. However, java doesn't support anonymous functions. Instead, we will have to pass something that implements an interface that we can use across both languages with JNI.

Here's the rough outline of what i'm thinking might be possible
- C++
  - makes class A
    - has log method
- java
  - class B implements class A (from C++)
    - log calls CrashlyticsLogger.log() with the correct args
  - passes instance of class B somehow back to C++
- C++
  - has function that takes class B instance
    - passes a pointer of instance.log to facebook's setLogHandler

maybe final thing would look similar to

``` C++
// --------------- C++ ---------------
#include <fb/log.h>
// somehow have this associated with a package of "myloggerproxy"

class LoggableFunction {
    public void log(int priority, String tag, String msg)
}

public void setLogProxy(LoggableFunction logProxy) {
    # setLogHandler comes from fb/log.h
    # pass a pointer of logProxy.log to setLogHandler
    setLogHandler(&logProxy.log)
}
```

``` Java
// --------------- Java ---------------
public class LogProxy {
    static {
        System.loadLibrary("myloggerproxy")
    }

    public static native void setLogProxy(LoggableFunction logProxy)
}

public class LoggerProxy implements LoggableFunction {
    public void log(int priority, String tag, String msg) {
        ReactNativeFabricLogger.getInstance().log(int, tag, msg)
    }
}

LogProxy.setLogProxy(new LoggerProxy())
```

I'm not sure if this will actually work, but I will try to test something like this out in this repo soon.

**Comment by sattaman** [comment]
did you get this to work in the end?

**Comment by Amurmurmur** [comment]
Same question anybody been able to make it work properly on android? 

On iOS seems like it logs even the booting stage of ReactNative js output

**Comment by sourabhkheterpal** [comment]
Hey Zach,

Following your tutorial, I have implemented everything. Crash due to `java` is logged in Fabric Panel but `javascript` crash is not logged.
I have change the function name to something which don't exist. it shows me red screen(react native error screen) comes but not logged into Fabric Panel.
I am in debug mode so i change `if` condition in `ReactNativeFabricLogger.java` file and everything redirect to `Crashlytics.log` .
I think i am missing something. Please help. 
Thanks.

**Comment by benjaminreid** [comment]
@sourabhkheterpal I ran into your issue, the `BuildConfig.DEBUG` was for some reason always evaluating to true (or just truthy) even when in release mode. So the Crashlytics logs never got run.

I solved this by adding my own build config variables into the`build.gradle`.

```gradle
debug {
    buildConfigField "boolean", "IS_DEBUG", "true"
}
release {
    buildConfigField "boolean", "IS_DEBUG", "false"
}
```

Then just updating the `DEBUG` variable.

```java
private void println(int priority, String tag, String msg) {
  if (BuildConfig.IS_DEBUG) {
    Log.println(priority, prefixTag(tag), msg);
  } else {
    Crashlytics.log(priority, prefixTag(tag), msg);
  }
}

private void println(int priority, String tag, String msg, Throwable tr) {
  if (BuildConfig.IS_DEBUG) {
    Log.println(priority, prefixTag(tag), getMsg(msg, tr));
  } else {
    Crashlytics.log(priority, prefixTag(tag), msg);
  }
}
```

Everything is now working as expected. 👍

**Comment by sourabhkheterpal** [comment]
@nouveller  Thanks for reply but i have some other issue. JAVA crash is logged into fabric but when i produce error due to JavaScript code its not logged in Fabric panel. for this i have change code like this:
```
private void println(int priority, String tag, String msg) {
   Crashlytics.log(priority, prefixTag(tag), msg);
}

private void println(int priority, String tag, String msg, Throwable tr) {
   Crashlytics.log(priority, prefixTag(tag), msg);
}
```
so that every time errors comes its logged into Crashlytics but somehow JavaScript error is not logged. Please let me know if you need more detail .

**Comment by okarakose** [comment]
@benjaminreid I am just asking, did you add `debuggable true` to your release variant ? in other case it can not be BuildConfig.DEBUG true for release variant because it is **false** by default.

`console.log`, `console.warn` and other variants did not pass to `FLog LoggingDelegate` class instance.

@zachgibb did you make it work ?

**Comment by kdastan** [comment]
@zachgibb same problem with JS, did you find solution ?

**Comment by niksoper** [comment]
@zachgibb any luck getting JS logs to show in crashlytics for android?

**Comment by PantTushar** [comment]
I have followed each and everything as per the article - https://www.mojotech.com/blog/fabric-integration-for-react-native-on-android/. I am able to see the javascript error logs. Below is the snapshot of the raw data from fabric.io. But can we have a fine tuned error log i.e. filename, methodname, line no etc.. 

Fatal Exception: com.facebook.react.common.JavascriptException: my error, stack:
value@552:4554
mountComponent@114:8746
mountComponent@114:1935
mountChildren@114:26285
initializeChildren@114:28042
mountComponent@114:28852
mountComponent@114:1935
performInitialMount@114:10038
mountComponent@114:8938
mountComponent@114:1935
performInitialMount@114:10038
mountComponent@114:8938
mountComponent@114:1935
mountChildren@114:26285
initializeChildren@114:28042
mountComponent@114:28852
mountComponent@114:1935
performInitialMount@114:10038
mountComponent@114:8938
mountComponent@114:1935
performInitialMount@114:10038
mountComponent@114:8938
mountComponent@114:1935
performInitialMount@114:10038
mountComponent@114:8938
mountComponent@114:1935
performInitialMount@114:10038
mountComponent@114:8938
mountComponent@114:1935
mountChildren@114:26285
initializeChildren@114:28042
mountComponent@114:28852
mountComponent@114:1935
mountChildren@114:26285
initializeChildren@114:28042
mountComponent@114:28852
mountComponent@114:1935
performInitialMount@114:10038
mountComponent@114:8938
mountComponent@114:1935
performInitialMount@114:10038
mountComponent@114:8938
mountComponent@114:1935
performInitialMount@114:10038
mountComponent@114:8938
mountComponent@114:1935
performInitialMount@114:10038
mountComponent@114:8938
mountComponent@114:1935
mountChildren@114:26285
initializeChildren@114:28042
mountComponent@114:28852
mountComponent@114:1935
mountChildren@114:26285
initializeChildren@114:28042
mountComponent@114:28852
mountComponent@114:1935
performInitialMount@114:10038
mountComponent@114:8938
mountComponent@114:1935
mountChildren@114:26285
initializeChildren@114:28042
mountComponent@114:28852
mountComponent@114:1935
performInitialMount@114:10038
mountComponent@114:8938
mountComponent@114:1935
mountChildren@114:26285
initializeChildren@114:28042
mountComponent@114:28852
mountComponent@114:1935
performInitialMount@114:10038
mountComponent@114:8938
mountComponent@114:1935
performInitialMount@114:10038
mountComponent@114:8938
mountComponent@114:1935
mountChildren@114:26285
initializeChildren@114:28042
mountComponent@114:28852
mountComponent@114:1935
performInitialMount@114:10038
mountComponent@114:8938
mountComponent@114:1935
performInitialMount@114:10038
mountComponent@114:8938
mountComponent@114:1935
performInitialMount@114:10038
mountComponent@114:8938
mountComponent@114:1935
performInitialMount@114:10038
mountComponent@114:8938
mountComponent@114:1935
updateChildren@114:25459
_reconcilerUpdateChildren@114:26047
_updateChildren@114:26918
updateChildren@114:26806
receiveComponent@114:28378
receiveComponent@114:2339
updateChildren@114:25392
_reconcilerUpdateChildren@114:26047
_updateChildren@114:26918
updateChildren@114:26806
receiveComponent@114:28378
receiveComponent@114:2339
_updateRenderedComponentWithNextElement@114:14747
_updateRenderedComponent@114:14597
_performComponentUpdate@114:13989
updateComponent@114:13054
receiveComponent@114:11734
receiveComponent@114:2339
_updateRenderedComponentWithNextElement@114:14747
_updateRenderedComponent@114:14597
_performComponentUpdate@114:13989
updateComponent@114:13054
receiveComponent@114:11734
receiveComponent@114:2339
_updateRenderedComponentWithNextElement@114:14747
_updateRenderedComponent@114:14597
_performComponentUpdate@114:13989
updateComponent@114:13054
receiveComponent@114:11734
receiveComponent@114:2339
_updateRenderedComponentWithNextElement@114:14747
_updateRenderedComponent@114:14597
_performComponentUpdate@114:13989
updateComponent@114:13054
performUpdateIfNecessary@114:11962
performUpdateIfNecessary@114:2705
be@113:10846
perform@114:3484
perform@114:3484
perform@114:4728
$o@114:4889
closeAll@114:4141
perform@114:3571
batchedUpdates@114:18574
Ce@113:10516
Q@113:6049
K@113:6111
_receiveRootNodeIDEvent@113:28847
receiveTouches@113:29227
value@30:3223
<unknown>@30:957
value@30:2652
value@30:929

**Comment by taschik** [comment]
Hi,

first of all thanks so much for the great blog post. I followed your instructions and event gave @benjaminreid 's idea with the IS_DEBUG a try. Unfortuantely, I don't see any logs at all in Crashlytics. I can see the stacktrace of my test crash but not any JS log:

```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=2; index=10
       at com.crashlytics.android.core.CrashTest.indexOutOfBounds(CrashTest.java:30)
       at com.crashlytics.android.core.CrashlyticsCore.crash(CrashlyticsCore.java:622)
       at com.crashlytics.android.Crashlytics.crash(Crashlytics.java:323)
       at com.smixx.fabric.SMXCrashlytics.crash(SMXCrashlytics.java:28)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
       at android.os.Looper.loop(Looper.java:193)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
       at java.lang.Thread.run(Thread.java:764)
```
I even added Crashlytics Logger for test reasons to every log line and I still see the console log when building for DEBUG:
```
    private void println(int priority, String tag, String msg) {
        if (BuildConfig.IS_DEBUG) {
            Log.println(priority, prefixTag(tag), msg);
            Crashlytics.log(priority, prefixTag(tag), msg);
        } else {
            Crashlytics.log(priority, prefixTag(tag), msg);
        }
    }
    private void println(int priority, String tag, String msg, Throwable tr) {
        if (BuildConfig.IS_DEBUG) {
            Log.println(priority, prefixTag(tag), getMsg(msg, tr));
            Crashlytics.log(priority, prefixTag(tag), msg);
        } else {
            Crashlytics.log(priority, prefixTag(tag), msg);
        }
    }
```
I am kinda clueless what else to try. Any ideas are welcome. 

I am running RN 0.55.4 and Android 9

**Comment by pilleanand** [comment]
Hi,

I have integrated crashlytics to react native android app, but still, am getting the java errors and not at all getting JS errors. 
I followed this [blog](https://www.mojotech.com/blog/fabric-integration-for-react-native-on-android/) 
Please help me in getting JS errors in crashlytics dashboard.

**Comment by ronilitman** [comment]
Any solution to the issue that console.log are not being logged to Crashlytics? Thank you!

**Comment by ntlyaraujo** [comment]
any solution ?
